Running spatial models...
Creating folder sub-01 in the directory /data/akitaitsev/data1/decoding_data3_script_based/SM/ridge
saving model data for subject  01...
Model <decoding_v6_script_based.myRidge object at 0x7f49f380b400>elapsed in 4786.21151971817 seconds.
Creating folder sub-01 in the directory /data/akitaitsev/data1/decoding_data3_script_based/SM/ridge_pca0.9
/data/akitaitsev/data1/code/decoding/decoding_v6_script_based.py:85: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  fig, ax = plt.subplots()
/data/akitaitsev/data1/code/decoding/decoding_v6_script_based.py:116: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  fig, ax = plt.subplots()
/data/akitaitsev/data1/code/decoding/decoding_v6_script_based.py:155: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  fig, (ax1, ax2) = plt.subplots(1,2, figsize=(16,9))
/data/akitaitsev/data1/code/decoding/decoding_v6_script_based.py:85: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  fig, ax = plt.subplots()
/data/akitaitsev/data1/code/decoding/decoding_v6_script_based.py:116: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  fig, ax = plt.subplots()
/data/akitaitsev/data1/code/decoding/decoding_v6_script_based.py:155: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  fig, (ax1, ax2) = plt.subplots(1,2, figsize=(16,9))
saving model data for subject  01...
Model <decoding_v6_script_based.myRidge object at 0x7f49f380b670>elapsed in 337.5992844104767 seconds.
Creating folder sub-01 in the directory /data/akitaitsev/data1/decoding_data3_script_based/SM/cca30
saving model data for subject  01...
Model CCA(n_components=30)elapsed in 6711.281367301941 seconds.
Running spatial temporal models
Running STM pca30_ridge
Creating folder sub-01 in the directory /data/akitaitsev/data1/decoding_data3_script_based/STM/pca30_ridge
saving model data for subject  01...
Model pca30_ridge elapsed in 54.0177788734436 seconds.
Running STM pca30_ridgePCA0.9
Creating folder sub-01 in the directory /data/akitaitsev/data1/decoding_data3_script_based/STM/pca30_ridgePCA0.9
saving model data for subject  01...
Model pca30_ridgePCA0.9 elapsed in 46.93460416793823 seconds.
Running STM pca30_cca300
Creating folder sub-01 in the directory /data/akitaitsev/data1/decoding_data3_script_based/STM/pca30_cca300
saving model data for subject  01...
Model pca30_cca300 elapsed in 4397.586668014526 seconds.
Running STM ridgePCA0.9_ridge
Traceback (most recent call last):
  File "analysis.py", line 70, in <module>
    STM = Pipeline([('spatial', spatial_decoder), ('temporal', temporal_decoder)])
  File "/home/akitaitsev/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/home/akitaitsev/anaconda3/lib/python3.8/site-packages/sklearn/pipeline.py", line 114, in __init__
    self._validate_steps()
  File "/home/akitaitsev/anaconda3/lib/python3.8/site-packages/sklearn/pipeline.py", line 159, in _validate_steps
    raise TypeError("All intermediate steps should be "
TypeError: All intermediate steps should be transformers and implement fit and transform or be the string 'passthrough' '<decoding_v6_script_based.myRidge object at 0x7f49d901ae20>' (type <class 'decoding_v6_script_based.myRidge'>) doesn't
Running spatial temporal models
Running STM ridgePCA0.9_ridge
Creating folder sub-01 in the directory /data/akitaitsev/data1/decoding_data3_script_based/STM/ridgePCA0.9_ridge
Traceback (most recent call last):
  File "analysis_tmp.py", line 46, in <module>
    dec.run_decoding(inp_dir, out_dir_iter, stim_param_dir, model_config, decoder=STM)
  File "/data/akitaitsev/data1/code/decoding/decoding_v6_script_based.py", line 559, in run_decoding
    predictions = decode(fmri_multirun, stim_multirun, decoder)     
  File "/data/akitaitsev/data1/code/decoding/decoding_v6_script_based.py", line 448, in decode
    predictions=cross_val_predict(decoder, fmri, stim, cv=kfold, n_jobs=n_splits)
  File "/home/akitaitsev/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/home/akitaitsev/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 771, in cross_val_predict
    prediction_blocks = parallel(delayed(_fit_and_predict)(
  File "/home/akitaitsev/anaconda3/lib/python3.8/site-packages/joblib/parallel.py", line 1042, in __call__
    self.retrieve()
  File "/home/akitaitsev/anaconda3/lib/python3.8/site-packages/joblib/parallel.py", line 921, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/akitaitsev/anaconda3/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/akitaitsev/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/akitaitsev/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGTERM(-15)}
